package pt.ua.airquality;

// Generated by Selenium IDE

import io.github.bonigarcia.seljup.SeleniumJupiter;

import static org.hamcrest.CoreMatchers.is;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;

import java.util.*;

import static org.hamcrest.MatcherAssert.assertThat;


@ExtendWith(SeleniumJupiter.class)
public class SeleniumInvalidWeatherTest {

    ChromeDriver driver;

    public SeleniumInvalidWeatherTest(ChromeDriver driver) {
        this.driver = driver;
    }

    @Test
    public void seleniumInvalidWeather() {
        // Test name: SeleniumInvalidWeather
        // Step # | name | target | value | comment
        // 1 | open | http://127.0.0.1:8080 |  |
        driver.get("http://127.0.0.1:8080");
        // 2 | setWindowSize | 1500x900 |  |
        driver.manage().window().setSize(new Dimension(1500, 900));
        // 3 | verifyTitle | Air Quality |  |
        assertThat(driver.getTitle(), is("Air Quality"));
        // 4 | assertElementPresent | id=inputCity |  |
        {
            List<WebElement> elements = driver.findElements(By.id("inputCity"));
            assert (elements.size() > 0);
        }
        // 5 | assertElementPresent | css=label |  |
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("label"));
            assert (elements.size() > 0);
        }
        // 6 | sendKeys | id=inputCity | invalido |
        driver.findElement(By.id("inputCity")).sendKeys("invalido");
        // 7 | click | css=.btn |  |
        driver.findElement(By.cssSelector(".btn")).click();
        // 8 | assertTitle | Error |  |
        assertThat(driver.getTitle(), is("Error"));
        // 9 | assertText | css=h1 | 404 |
        assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("404"));
    }
}
