package pt.ua.airquality;
// Generated by Selenium IDE

import io.github.bonigarcia.seljup.SeleniumJupiter;

import static org.hamcrest.CoreMatchers.is;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;

import java.util.*;

import static org.hamcrest.MatcherAssert.assertThat;


@ExtendWith(SeleniumJupiter.class)
public class SeleniumValidWeatherTest {

    ChromeDriver driver;

    public SeleniumValidWeatherTest(ChromeDriver driver) {
        this.driver = driver;
    }

    @Test
    public void seleniumValidWeather() {
        // Test name: SeleniumValidWeather
        // Step # | name | target | value | comment
        // 1 | open | http://localhost:8080/ |  |
        driver.get("http://127.0.0.1:8080/");
        // 2 | setWindowSize | 1500x700 |  |
        driver.manage().window().setSize(new Dimension(1500, 700));
        // 3 | assertTitle | Air Quality |  |
        assertThat(driver.getTitle(), is("Air Quality"));
        // 4 | verifyElementPresent | css=label |  |
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("label"));
            assert (elements.size() > 0);
        }
        // 5 | verifyElementPresent | id=inputCity |  |
        {
            List<WebElement> elements = driver.findElements(By.id("inputCity"));
            assert (elements.size() > 0);
        }
        // 6 | sendKeys | id=inputCity | sao paulo |
        driver.findElement(By.id("inputCity")).sendKeys("sao paulo");
        // 7 | click | css=.btn |  |
        driver.findElement(By.cssSelector(".btn")).click();
        // 8 | assertElementPresent | css=tr:nth-child(1) > td:nth-child(2) |  |
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(1) > td:nth-child(2)"));
            assert (elements.size() > 0);
        }
        // 9 | assertText | css=tr:nth-child(1) > td:nth-child(2) | sao paulo |
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).getText(), is("sao paulo"));
    }
}
